export {
    splitClassString,
    getClassNames,
    makeSafeText,
    getSafeText,
    getEventTarget,
    autocaptureCompatibleElements,
    getParentElement,
    DEFAULT_CONTENT_IGNORELIST_WITH_STEPPERS,
    shouldCaptureDeadClick,
    isTextSelectionTarget,
    shouldCaptureRageclick,
    shouldSkipDeadClick,
    shouldCaptureDomEvent,
    shouldCaptureElement,
    isSensitiveElement,
    shouldCaptureValue,
    isAngularStyleAttr,
    getDirectAndNestedSpanText,
    getNestedSpanText,
    getElementsChainString,
} from '@posthog/browser-common/utils/autocapture-utils'
export type {
    AutocaptureConfig,
    DeadClickCaptureConfig,
    RageClickConfig,
} from '@posthog/browser-common/utils/autocapture-utils'
