export {
    DisplaySurveyType,
    SurveyEventName,
    SurveyEventProperties,
    SurveyEventType,
    SurveyPosition,
    SurveyQuestionBranchingType,
    SurveyQuestionType,
    SurveySchedule,
    SurveyTabPosition,
    SurveyType,
    SurveyWidgetType,
} from '@posthog/browser-common/surveys-types'
export type {
    PropertyOperator,
    PropertyFilters,
    SurveyEventWithFilters,
    SurveyAppearance,
    SurveyQuestion,
    SurveyQuestionDescriptionContentType,
    BasicSurveyQuestion,
    LinkSurveyQuestion,
    RatingSurveyQuestion,
    MultipleSurveyQuestion,
    Survey,
    SurveyWithTypeAndAppearance,
    SurveyActionType,
    ActionStepStringMatching,
    ActionStepType,
    SurveyCallback,
    SurveyElement,
    SurveyRenderReason,
    DisplaySurveyPopoverOptions,
    DisplaySurveyOptions,
    SurveyConfig,
    SurveyResponseValue,
} from '@posthog/browser-common/surveys-types'
