name: "Setup Workspace Environment"
description: "Sets up a Node.js environment and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm cache directory path
      id: pnpm-cache-dir
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org

    - uses: actions/cache@v4
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-

    - name: Install package.json dependencies with pnpm
      shell: bash
      run: pnpm install --frozen-lockfile
