packages:
  - packages/*
  - packages/rrweb/*
  - packages/rrweb/plugins/*
  - tooling/*
  - "!**/playground/**"
  - "!**/examples/**"

catalog:
  "@babel/core": ^7.27.1
  "@babel/plugin-syntax-decorators": ^7.27.1
  "@babel/plugin-transform-exponentiation-operator": ^7.27.1
  "@babel/plugin-transform-nullish-coalescing-operator": ^7.27.1
  "@babel/plugin-transform-react-jsx": ^7.27.1
  "@babel/preset-env": ^7.27.1
  "@babel/preset-react": ^7.27.1
  "@babel/preset-typescript": ^7.27.1
  "@posthog/cli": ~0.5.20
  "@rslib/core": 0.10.6
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/preact": ^3.2.4
  "@testing-library/react": ^16.3.0
  "@types/jest": ^29.5.14
  "@types/react": ^19.2.7
  jest: 29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-environment-node: ^29.7.0
  jest-expo: ^47.0.1
  react: ^19.2.1
  react-dom: ^19.2.1
  react-test-renderer: ^19.2.1
  rollup: ^4.53.3
  ts-jest: 29.4.0
  tslib: ^2.5.0
  typescript: 5.8.2
  vite: ^6.2.0
  vite-plugin-dts: ^4.5.4
  esbuild-plugin-umd-wrapper: ^3.0.0

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - node-forge@1.3.2
  - next@15.5.7
  - "@next/env@15.5.7"
  - "@posthog/cli"

supportedArchitectures:
  cpu: [x64, arm64v8, arm64]
  os: [linux, darwin]
