// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CaptureEventProcedure from "../capture_event_procedure";

export type CaptureEventArgs = __Infer<typeof CaptureEventProcedure.params>;
export type CaptureEventResult = __Infer<typeof CaptureEventProcedure.returnType>;

