import type { Metadata } from 'next'
import PHProvider from './posthog'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <PHProvider>{children}</PHProvider>
            </body>
        </html>
    )
}
