export const BRAND_COLOR = '#1D4AFF'

export const styles = {
    chatHeader: (brandColor: string) => ({
        backgroundColor: brandColor,
        color: 'white',
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        padding: 16,
    }),
    chatHeaderTitle: {
        fontSize: 12,
        fontWeight: 'bold' as const,
    },
    assistantMessageContainer: {
        width: 284,
        display: 'flex',
    },
    messageContentContainer: {
        display: 'flex',
        flexDirection: 'column' as const,
        marginLeft: 8,
        marginTop: 4,
    },
    assistantName: {
        fontSize: 10,
        color: 'rgb(146, 169, 193)',
    },
    assistantMessageText: (brandColor: string) => ({
        fontSize: 12,
        backgroundColor: brandColor,
        color: 'white',
        paddingLeft: 14,
        paddingRight: 14,
        paddingTop: 8,
        paddingBottom: 9,
        borderRadius: 10,
        overflow: 'hidden',
        textAlign: 'left' as const,
    }),
    messageTimestamp: {
        fontSize: 10,
        color: 'rgb(146, 169, 193)',
    },
    userMessageContainerOuter: {
        width: '100%',
        display: 'flex',
        justifyContent: 'flex-end',
    },
    userMessageContainerInner: {
        width: 284,
    },
    userMessageContentContainer: {
        display: 'flex',
        flexDirection: 'column' as const,
        marginLeft: 8,
        marginTop: 4,
        alignItems: 'flex-end',
    },
    userMessageText: {
        fontSize: 12,
        backgroundColor: 'rgb(240, 242, 245)',
        color: 'rgb(28, 41, 59)',
        paddingLeft: 14,
        paddingRight: 14,
        paddingTop: 8,
        paddingBottom: 9,
        borderRadius: 10,
        overflow: 'hidden',
        textAlign: 'right' as const,
    },
    chatMessagesContainer: {
        background: 'white',
        height: 366,
        padding: 8,
        overflowY: 'auto' as const,
    },
    chatInputContainer: (brandColor: string) => ({
        display: 'flex',
        padding: 8,
        borderTop: `1px solid ${brandColor}`,
    }),
    chatInput: {
        width: '100%',
        height: 40,
        borderRadius: 8,
        border: 'none',
        outline: 'none',
        padding: '0 10px',
        boxSizing: 'border-box' as const,
    },
    sendButton: (brandColor: string, isSending: boolean) => ({
        cursor: 'pointer',
        backgroundColor: brandColor,
        color: 'white',
        borderRadius: 10,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '5px 10px',
        fontSize: 12,
        fontWeight: 300,
        opacity: isSending ? 0.5 : 1,
    }),
    chatContainer: (isVisible: boolean) => ({
        position: 'fixed' as const,
        right: 14,
        bottom: 75,
        transition: 'width .15s ease-in-out !important',
        borderRadius: 12,
        backgroundColor: '#fff',
        boxShadow: '0 6px 6px 0 rgba(0,0,0,.02), 0 8px 24px 0 rgba(0,0,0,.12)',
        width: 360,
        visibility: isVisible ? ('visible' as const) : ('hidden' as const),
        overflow: 'hidden',
        zIndex: 9999,
    }),
    chatBubble: (brandColor: string) => ({
        position: 'fixed' as const,
        right: 14,
        bottom: 14,
        borderRadius: 54,
        width: 54,
        height: 54,
        backgroundColor: brandColor,
        color: 'white',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        cursor: 'pointer',
    }),
    chatBubbleIconContainer: {
        position: 'relative' as const,
        width: 24,
        height: 24,
    },
}
