name: "Posthog auto upgrade"
description: "Upgrade a package in main posthog repository"

inputs:
  package_name:
    description: "package name to upgrade"
    required: true
  package_version:
    description: "package version to upgrade to"
    required: true
  deployer_app_id:
    description: "deployer app id"
    required: true
  deployer_app_private_key:
    description: "deployer app private key"
    required: true
  github_bot_token:
    description: "github bot token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out main repo
      uses: actions/checkout@v2
      with:
        repository: "PostHog/posthog"
        token: ${{ inputs.github_bot_token }}

    - uses: pnpm/action-setup@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm

    - name: Install new package version in main repo
      id: pnpm-upgrade
      shell: bash
      run: |
        OUTGOING_VERSION=$(jq '.dependencies["${{ inputs.package_name }}"]' package.json -r)
        echo "outgoing-version=$OUTGOING_VERSION" >> "$GITHUB_OUTPUT"
        for i in $(seq 1 $RETRY_TIMES); do
            # Retry loop because of npm being _eventually_ consistent
            if pnpm -w upgrade ${{ inputs.package_name }}@${{ inputs.package_version }}; then
                break
            else
                [ $i -ne $RETRY_TIMES ] && sleep $RETRY_WAIT_SECONDS || false
            fi
        done
      env:
        RETRY_TIMES: 20
        RETRY_WAIT_SECONDS: 5

    - name: Create main repo pull request
      id: main-repo-pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.github_bot_token }}
        commit-message: "chore(deps): Update ${{ inputs.package_name }} to ${{ inputs.package_version }}"
        branch: ${{ replace(replace(inputs.package_name, '@', ''), '/', '-') }}-${{ inputs.package_version }}
        delete-branch: true
        labels: automerge
        title: "chore(deps): Update ${{ inputs.package_name }} to ${{ inputs.package_version }}"
        body: |
          ## Changes

          ${{ inputs.package_name }} version ${{ inputs.package_version }} has been released. This updates PostHog to use it.

          https://github.com/PostHog/posthog-js/compare/${{ inputs.package_name }}@${{ steps.pnpm-upgrade.outputs.outgoing-version }}...${{ inputs.package_name }}@${{ inputs.package_version }} • [GitHub releases](https://github.com/PostHog/posthog-js/releases) • [npm releases](https://www.npmjs.com/package/${{ inputs.package_name }}?activeTab=version)

    - name: Output pull request result
      shell: bash
      run: |
        echo "PostHog pull request for ${{ inputs.package_name }} version ${{ inputs.package_version }} ready: ${{ steps.main-repo-pr.outputs.pull-request-url }}"

    - name: get deployer token
      id: deployer
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ inputs.deployer_app_id }}
        private_key: ${{ inputs.deployer_app_private_key }}

    - name: Stamp PR
      shell: bash
      run: |
        # unbelievably github has a race condition where if you commit and
        # approve too quickly on a PR with "auto-merge" enabled it can miss
        # the new commit in the merge commit (but it looks like the PR has the change)
        # Sleep 5 should work
        sleep 5
        pull_number=${{ steps.main-repo-pr.outputs.pull-request-number }}
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ steps.deployer.outputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/posthog/posthog/pulls/${pull_number}/reviews \
        -d '{"body":"${{ inputs.package_name }} auto approved.","event":"APPROVE","comments":[]}'
