virtualStoreDir: ../../../../node_modules/.pnpm

packages:
  - "." # TODO delete this file and make the root workspace's file respect exclusion rules for this folder - weirdly tricky to do so
  - "../.."
  - "../../../react"
  - "../../../../tooling/*"

catalog:
  tsup: "^8.5.0"
  typescript: "^5.5.4"
  rollup: "^4.44.1"
  tslib: "^2.5.0"
  jest: "^29.7.0"
  jest-environment-jsdom: "^29.7.0"
  jest-environment-node: "^29.7.0"
  jest-expo: "^47.0.1"
  "@types/jest": "^29.7.0"
  ts-jest: "^29.0.0"
