// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const FeatureFlag = __t.object("FeatureFlag", {
  distinctId: __t.string(),
  flagsJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type FeatureFlag = __Infer<typeof FeatureFlag>;

export const FlagRequest = __t.object("FlagRequest", {
  distinctId: __t.string(),
});
export type FlagRequest = __Infer<typeof FlagRequest>;

export const Person = __t.object("Person", {
  name: __t.string(),
  addedBy: __t.identity(),
});
export type Person = __Infer<typeof Person>;

