name: 'Notify Slack - Release Approval Needed'
description: 'Sends a Slack notification when a release needs approval'

inputs:
    slack_bot_token:
        description: 'Slack Bot Token'
        required: true
    slack_channel_id:
        description: 'Slack Channel ID'
        required: true
    slack_user_group_id:
        description: 'Slack User Group ID for mentions'
        required: true

outputs:
    slack_ts:
        description: 'Slack message timestamp (for threading replies)'
        value: ${{ steps.slack.outputs.ts }}

runs:
    using: 'composite'
    steps:
        - name: Get latest tag info
          id: get-tag-info
          shell: bash
          run: |
              # Fetch all tags
              git fetch --tags --force

              # Get the most recent tag (sorted by date, not version)
              LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)

              if [ -z "$LATEST_TAG" ]; then
                echo "No tags found, using initial commit"
                LATEST_TAG=$(git rev-list --max-parents=0 HEAD)
              fi

              echo "latest_tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"

              # Get current commit SHA
              CURRENT_SHA=$(git rev-parse HEAD)
              echo "current_sha=$CURRENT_SHA" >> "$GITHUB_OUTPUT"
              echo "current_sha_short=${CURRENT_SHA:0:7}" >> "$GITHUB_OUTPUT"

              # Get commit count
              COMMIT_COUNT=$(git rev-list --count "$LATEST_TAG"..HEAD 2>/dev/null || echo "N/A")
              echo "commit_count=$COMMIT_COUNT" >> "$GITHUB_OUTPUT"

        - name: Send Slack notification
          id: slack
          uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
          with:
              method: chat.postMessage
              token: ${{ inputs.slack_bot_token }}
              payload: |
                  {
                    "channel": "${{ inputs.slack_channel_id }}",
                    "text": "🚀 Release Approval Needed for ${{ github.repository }}",
                    "blocks": [
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": "🚀 Release Approval Needed - ${{ github.repository }}",
                          "emoji": true
                        }
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "A new release is ready for approval in the `${{ github.repository }}` repository."
                        }
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Repository:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Latest Tag:*\n`${{ steps.get-tag-info.outputs.latest_tag }}`"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Current Commit:*\n`${{ steps.get-tag-info.outputs.current_sha_short }}`"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Commits since tag:*\n${{ steps.get-tag-info.outputs.commit_count }}"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "<!subteam^${{ inputs.slack_user_group_id }}|@group-client-libraries> Please review and approve the release."
                        }
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "View Diff on GitHub",
                              "emoji": true
                            },
                            "url": "https://github.com/${{ github.repository }}/compare/${{ steps.get-tag-info.outputs.latest_tag }}...main"
                          },
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "Approve/Reject on GitHub",
                              "emoji": true
                            },
                            "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                            "style": "primary"
                          }
                        ]
                      }
                    ]
                  }
