packages:
    - '.'

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
    - '@posthog/core@1.47.0'
    - '@posthog/types@1.403.0'
    - '@react-native/asset-utils@0.87.0'
    - '@react-native/babel-plugin-codegen@0.87.0'
    - '@react-native/babel-preset@0.87.0'
    - '@react-native/codegen@0.87.0'
    - '@react-native/community-cli-plugin@0.87.0'
    - '@react-native/debugger-frontend@0.87.0'
    - '@react-native/debugger-shell@0.87.0'
    - '@react-native/dev-middleware@0.87.0'
    - '@react-native/gradle-plugin@0.87.0'
    - '@react-native/js-polyfills@0.87.0'
    - '@react-native/metro-babel-transformer@0.87.0'
    - '@react-native/metro-config@0.87.0'
    - '@react-native/normalize-colors@0.87.0'
    - '@react-native/typescript-config@0.87.0'
    - '@react-native/virtualized-lists@0.87.0'
    - hermes-compiler@260318099.0.1
    - react-native@0.87.0
