import snapshot, {
  snapshotWithBudget,
  type SnapshotWithBudgetOptions,
  serializeNodeWithId,
  transformAttribute,
  ignoreAttribute,
  visitSnapshot,
  cleanupSnapshot,
  needMaskingText,
  classMatchesRegex,
  slimDOMDefaults,
  IGNORED_NODE,
  DEFAULT_MAX_DEPTH,
  wasMaxDepthReached,
  resetMaxDepthState,
  resetStylesheetLoadTracking,
  genId,
} from './snapshot';
export * from './types';
export * from './utils';

export {
  snapshot,
  snapshotWithBudget,
  type SnapshotWithBudgetOptions,
  serializeNodeWithId,
  transformAttribute,
  ignoreAttribute,
  visitSnapshot,
  cleanupSnapshot,
  needMaskingText,
  classMatchesRegex,
  slimDOMDefaults,
  IGNORED_NODE,
  DEFAULT_MAX_DEPTH,
  wasMaxDepthReached,
  resetMaxDepthState,
  resetStylesheetLoadTracking,
  genId,
};
