// Re-exports the @posthog/rrweb-types package so downstream consumers of
// posthog-js can import shared rrweb types via `posthog-js/rrweb-types`
// instead of depending on the underlying workspace package directly.
//
// rrweb-types is types-only, so the generated dist/rrweb-types.js file is
// effectively empty — the value of this entrypoint comes from its bundled
// .d.ts (generated by rollup-plugin-dts). The sibling package.json that
// maps the subpath lives at packages/browser/rrweb-types/package.json.
export * from '@posthog/rrweb-types'
