export * from './extensions/sentry-integration'
export * from './extensions/express'
export * from './types'
export { FeatureFlagError } from '@posthog/core'
export type { FeatureFlagErrorType } from '@posthog/core'
