import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PHProvider } from '@/app/components/providers/ph-provider'
import dynamic from 'next/dynamic'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PostHog & Create Next App",
  description: "Generated by create next app",
};


const PostHogPageView = dynamic(() => import('@/app/components/posthog/page-view'), {
  ssr: false,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PHProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <PostHogPageView />
          {children}
        </body>
      </PHProvider>
    </html>
  );
}
