name: 'CD'

on:
    push:
        branches:
            - typescript

jobs:
    check-package-version:
        name: Check package version and detect an update
        runs-on: ubuntu-20.04
        outputs:
            committed-version: ${{ steps.check-package-version.outputs.committed-version }}
            published-version: ${{ steps.check-package-version.outputs.published-version }}
            is-new-version: ${{ steps.check-package-version.outputs.is-new-version }}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Check package version and detect an update
              id: check-package-version
              uses: PostHog/check-package-version@v2

    release:
        name: Publish release if new version
        runs-on: ubuntu-20.04
        needs: check-package-version
        if: needs.check-package-version.outputs.is-new-version == 'true'
        env:
            COMMITTED_VERSION: ${{ needs.check-package-version.outputs.committed-version }}
            PUBLISHED_VERSION: ${{ needs.check-package-version.outputs.published-version }}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.POSTHOG_BOT_GITHUB_TOKEN }}

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Publish the package in the npm registry
              run: npm publish --access public --tag alpha
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}