name: ES5 support check

on:
  - pull_request

jobs:
  ssr:
    name: Build and check ES5/ES6 support
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          build: true

      - name: Run es-check to check if our ie11 bundle is ES5 compatible
        run: npx es-check@7.2.1 es5 packages/browser/dist/array.full.es5.js

      - name: Run es-check to check if our main bundle is ES6 compatible
        run: npx es-check@7.2.1 es6 packages/browser/dist/array.full.js
