name: ES5 support check

on:
  - pull_request

jobs:
  ssr:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.x.x
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - run: pnpm install && pnpm build

      - name: Run es-check to check if our ie11 bundle is ES5 compatible
        run: npx es-check@7.2.1 es5 dist/array.full.es5.js
