name: Playwright Integration Tests
on: [pull_request]
env:
  POSTHOG_PROJECT_KEY: "${{ secrets.POSTHOG_PROJECT_KEY }}"
  POSTHOG_API_KEY: "${{ secrets.POSTHOG_API_KEY }}"
  POSTHOG_API_HOST: https://us.i.posthog.com
  POSTHOG_API_PROJECT: 11213

jobs:
  browsers:
    name: Test on ${{ matrix.name }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        browser:
          - "chromium"
          - "firefox"
          - "webkit"
        include:
          - browser: "chromium"
            name: Chrome
          - browser: "firefox"
            name: Firefox
          - browser: "webkit"
            name: Safari

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Set up posthog-js
        run: pnpm build-rollup
        working-directory: packages/browser

      - name: Install Playwright Browsers
        run: pnpm exec playwright install ${{ matrix.browser }} --with-deps
        working-directory: packages/browser

      - name: Run ${{ matrix.name }} test
        timeout-minutes: 10
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          RUN_ID: ${{ github.run_id }}
          BROWSER: ${{ matrix.browser }}
        run: pnpm exec playwright test --config playwright.config.integration.ts --project ${{ matrix.browser }}
        working-directory: packages/browser
