name: Playwright Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 8.x.x
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
