name: Node SDK Compliance Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/node/**'
      - 'packages/core/**'
      - 'compliance/node/**'
      - '.github/workflows/sdk-compliance-tests-node.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/node/**'
      - 'packages/core/**'
      - 'compliance/node/**'
      - '.github/workflows/sdk-compliance-tests-node.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  test-node-sdk:
    uses: PostHog/posthog-sdk-test-harness/.github/workflows/test-sdk-action.yml@02c049e529001d02f37a534745678e057d371fb0
    with:
      adapter-dockerfile: compliance/node/Dockerfile
      adapter-context: .
      test-harness-version: "0.10.0"
      report-name: node-sdk-compliance-report
