name: Browser SDK Compliance Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/browser/**'
      - 'packages/core/**'
      - 'compliance/browser/**'
      - '.github/workflows/sdk-compliance-tests-browser.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/browser/**'
      - 'packages/core/**'
      - 'compliance/browser/**'
      - '.github/workflows/sdk-compliance-tests-browser.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  test-browser-sdk:
    uses: PostHog/posthog-sdk-test-harness/.github/workflows/test-sdk-action.yml@68498bcf3ae95ac941476e6ca3d42d6086e1c7fd
    with:
      adapter-dockerfile: compliance/browser/Dockerfile
      adapter-context: .
      test-harness-version: "0.9.0"
      report-name: browser-sdk-compliance-report
